/**
 * Bus Simulator - Brake System (Phase 10B Task 10)
 *
 * ONE authoritative owner of braking force.
 *
 * Responsibilities:
 *   - service brake / progressive braking
 *   - brake force calculation
 *   - front/rear brake bias
 *   - braking based on vehicle speed
 *   - braking based on available wheel load
 *   - brake fade from sustained heavy braking
 *   - brake temperature and cooling
 *   - maximum braking force
 *   - lightweight ABS model (wheel slip threshold, pressure restore)
 *   - integration with weather friction and suspension wheel-load
 *
 * Does NOT duplicate acceleration, steering, transmission, fuel, collision
 * damage, or weather friction. MovementSystem remains the movement/physics
 * coordinator. The old BrakingSystem inside MovementSystem is disabled so
 * there is exactly one authoritative braking path.
 */

(function () {
  'use strict';

  const EventManager = (typeof window !== 'undefined' && window.BusSim && window.BusSim.EventManager) ||
    (typeof require !== 'undefined' ? require('../engine/EventManager') : null);

  const DEFAULT_BRAKE = {
    maxBrakeForce: 22000,     // N (bus-scale)
    frontBias: 0.62,          // 0..1 fraction of force to front axle
    brakeTempMax: 600,        // deg C
    brakeTempStart: 20,       // deg C
    fadeStartTemp: 300,       // deg C
    fadeMaxTemp: 500,         // deg C
    fadeMinFactor: 0.35,      // minimum brake force factor when hot
    coolingRate: 25,          // deg C/s when moving
    idleCoolingRate: 4,       // deg C/s when stopped
    absSlipThreshold: 0.18,   // wheel slip ratio that triggers ABS
    absRestoreRate: 0.6,      // pressure restore per second when grip returns
    absMaxCycles: 6           // safety cap on ABS modulation per update
  };

  function BrakeSystem() {
    this._vehicles = new Map();
    this._modules = null;
    this._active = true;
  }

  BrakeSystem.prototype.init = function (modules) {
    this._modules = modules;
    this._vehicles = new Map();
    this._active = true;
  };

  BrakeSystem.prototype.update = function (dt) {
    if (!this._active) return;
    for (const [, state] of this._vehicles) {
      this._updateBrake(state, dt);
    }
  };

  // MovementSystem calls this before the physics step so brake force,
  // temperature, fade, and ABS are current for the deceleration gate.
  BrakeSystem.prototype.updateVehicle = function (vehicle, dt) {
    if (!vehicle) return;
    const state = this.ensureBrake(vehicle);
    if (!state) return;
    state.speed = typeof vehicle.speed === 'number' ? vehicle.speed : 0;
    state.targetSpeed = typeof vehicle.targetSpeed === 'number' ? vehicle.targetSpeed : 0;
    state.brakeInput = typeof vehicle._brakeInput === 'number' ? vehicle._brakeInput : 0;
    state.handbrake = !!vehicle._handbrake;
    state.steering = typeof vehicle.steering === 'number' ? vehicle.steering : 0;
state.roadFriction = (typeof vehicle.roadFrictionMultiplier === 'number')
      ? vehicle.roadFrictionMultiplier : 1.0;
    // Phase 10B Task 12: consult the road surface's braking grip
    // multiplier. RoadSurfaceSystem owns surface data; BrakeSystem only
    // reads the braking-grip component it needs.
    const surface = (typeof vehicle.getRoadSurface === 'function')
      ? vehicle.getRoadSurface() : null;
    state.brakingGrip = (surface && typeof surface.brakingGripMultiplier === 'number')
      ? surface.brakingGripMultiplier : 1.0;
    // Suspension wheel-load (optional integration)
    const susp = (typeof vehicle.getSuspension === 'function') ? vehicle.getSuspension() : null;
    if (susp) {
      state.frontLoad = susp.frontLoad;
      state.rearLoad = susp.rearLoad;
    }
    this._updateBrake(state, dt);
  };

  BrakeSystem.prototype._updateBrake = function (state, dt) {
    if (!state) return;
    const dtSafe = dt > 0 ? dt : 0.016;

// ---- Brake temperature ----
    // Heat is generated by brake force applied; cooled when moving or idle.
    const brakeActive = state.brakeInput > 0 || state.handbrake;
    if (brakeActive) {
      // Heat generation scales with brake input and speed for realism.
      const speedKmh = Math.abs(state.speed || 0);
      const heatGen = (state.brakeInput * 200 + (state.handbrake ? 300 : 0)) * (1 + speedKmh / 50);
      state.brakeTemp = Math.min(state.brakeTempMax, state.brakeTemp + heatGen * dtSafe);
    }
    // Cooling
    const speedKmh = Math.abs(state.speed || 0);
    const cooling = speedKmh > 0.5 ? state.coolingRate : state.idleCoolingRate;
    state.brakeTemp = Math.max(state.brakeTempStart, state.brakeTemp - cooling * dtSafe);

    // ---- Brake fade ----
    // Brake force is reduced as temperature rises past fadeStartTemp.
    let fadeFactor = 1.0;
    if (state.brakeTemp > state.fadeStartTemp) {
      const t = Math.min(1, (state.brakeTemp - state.fadeStartTemp) / (state.fadeMaxTemp - state.fadeStartTemp));
      fadeFactor = Math.max(state.fadeMinFactor, 1 - t * (1 - state.fadeMinFactor));
    }
    state.fadeFactor = fadeFactor;

    // ---- Progressive brake force ----
    // Brake force scales with input (0..1), speed, and available wheel load.
    const brakeInput = Math.max(0, Math.min(1, state.brakeInput || 0));
    const handbrakeForce = state.handbrake ? 0.5 : 0;
    const totalInput = Math.min(1, brakeInput + handbrakeForce);
    const speedFactor = Math.min(1, Math.abs(state.speed || 0) / 40);
    const loadFactor = this._computeLoadFactor(state);
    const rawForce = state.maxBrakeForce * totalInput * speedFactor * loadFactor * fadeFactor;

// ---- ABS modulation ----
    // Simulate wheel slip: higher slip when brake force exceeds available grip.
    // availableGrip is scaled to be comparable to maxBrakeForce so ABS
    // modulates rather than fully releasing on low-friction roads.
    // Phase 10B Task 12: braking grip from the road surface is multiplied
    // in. RoadSurfaceSystem owns surface data; BrakeSystem only reads it.
    const availableGrip = state.roadFriction * state.brakingGrip * state.maxBrakeForce;
    const slipRatio = Math.min(1, rawForce / Math.max(1, availableGrip));
    let absActive = false;
    let absPressure = rawForce;
    if (slipRatio > state.absSlipThreshold) {
      absActive = true;
      // Reduce brake pressure when slip exceeds threshold, but keep enough
      // pressure to maintain stopping power (ABS modulates, does not fully release).
      const excess = slipRatio - state.absSlipThreshold;
      absPressure = rawForce * (1 - excess * 0.5);
      // Restore pressure when grip returns
      absPressure = Math.max(0, absPressure + state.absRestoreRate * availableGrip * dtSafe);
    }
    state.absActive = absActive;
    state.slipRatio = slipRatio;
    state.brakeForce = Math.max(0, absPressure);

    // ---- Front/rear bias ----
    const frontForce = state.brakeForce * state.frontBias;
    const rearForce = state.brakeForce * (1 - state.frontBias);
    state.frontBrakeForce = frontForce;
    state.rearBrakeForce = rearForce;

    // ---- Apply deceleration to the vehicle ----
    // ONE authoritative braking path: BrakeSystem writes the deceleration
    // directly onto vehicle.speed. MovementSystem's old BrakingSystem is
    // disabled so there is no duplicate braking.
    const decel = (state.brakeForce / Math.max(1, state.mass)) * 3.6; // km/h per second
    if (state.speed > 0) {
      state.speed = Math.max(0, state.speed - decel * dtSafe);
    } else if (state.speed < 0) {
      state.speed = Math.min(0, state.speed + decel * dtSafe);
    }
    state.deceleration = decel;
  };

  BrakeSystem.prototype._computeLoadFactor = function (state) {
    // Use suspension wheel-load if available; otherwise assume even split.
    if (state.frontLoad && state.rearLoad) {
      const total = state.frontLoad + state.rearLoad;
      if (total > 0) return total / Math.max(1, state.mass);
    }
    return 1.0;
  };

  // ---- Vehicle integration helpers ----
  BrakeSystem.prototype.ensureBrake = function (vehicle) {
    if (!vehicle) return null;
    if (vehicle._brake && vehicle._brake.__owner === this) {
      return vehicle._brake;
    }
    const state = this._createBrake(vehicle);
    vehicle._brake = state;
    return state;
  };

  BrakeSystem.prototype._createBrake = function (vehicle) {
    const defaults = vehicle && vehicle.brakeConfig ? vehicle.brakeConfig : DEFAULT_BRAKE;
    const state = {
      __owner: this,
      maxBrakeForce: defaults.maxBrakeForce || DEFAULT_BRAKE.maxBrakeForce,
      frontBias: defaults.frontBias || DEFAULT_BRAKE.frontBias,
      brakeTempMax: defaults.brakeTempMax || DEFAULT_BRAKE.brakeTempMax,
      brakeTemp: defaults.brakeTempStart || DEFAULT_BRAKE.brakeTempStart,
      brakeTempStart: defaults.brakeTempStart || DEFAULT_BRAKE.brakeTempStart,
      fadeStartTemp: defaults.fadeStartTemp || DEFAULT_BRAKE.fadeStartTemp,
      fadeMaxTemp: defaults.fadeMaxTemp || DEFAULT_BRAKE.fadeMaxTemp,
      fadeMinFactor: defaults.fadeMinFactor || DEFAULT_BRAKE.fadeMinFactor,
      coolingRate: defaults.coolingRate || DEFAULT_BRAKE.coolingRate,
      idleCoolingRate: defaults.idleCoolingRate || DEFAULT_BRAKE.idleCoolingRate,
      absSlipThreshold: defaults.absSlipThreshold || DEFAULT_BRAKE.absSlipThreshold,
      absRestoreRate: defaults.absRestoreRate || DEFAULT_BRAKE.absRestoreRate,
      absMaxCycles: defaults.absMaxCycles || DEFAULT_BRAKE.absMaxCycles,
      mass: (vehicle && typeof vehicle.mass === 'number') ? vehicle.mass : 8000,
      speed: (vehicle && typeof vehicle.speed === 'number') ? vehicle.speed : 0,
      targetSpeed: 0,
      brakeInput: 0,
      handbrake: false,
      steering: 0,
      roadFriction: 1.0,
      frontLoad: 0,
      rearLoad: 0,
      brakeForce: 0,
      frontBrakeForce: 0,
      rearBrakeForce: 0,
      deceleration: 0,
      fadeFactor: 1.0,
      absActive: false,
      slipRatio: 0
    };
    this._vehicles.set(vehicle.id || ('v_' + Math.random().toString(36).slice(2)), state);
    return state;
  };

  BrakeSystem.prototype.getBrake = function (vehicle) {
    if (!vehicle) return null;
    return vehicle._brake || null;
  };

  BrakeSystem.prototype.resetBrake = function (vehicle) {
    const state = this.ensureBrake(vehicle);
    if (!state) return;
    state.brakeForce = 0;
    state.frontBrakeForce = 0;
    state.rearBrakeForce = 0;
    state.deceleration = 0;
    state.fadeFactor = 1.0;
    state.absActive = false;
    state.slipRatio = 0;
    state.brakeInput = 0;
    state.handbrake = false;
  };

  BrakeSystem.prototype.serializeBrake = function (vehicle) {
    const state = this.getBrake(vehicle);
    if (!state) return null;
    return {
      brakeTemp: state.brakeTemp,
      brakeForce: state.brakeForce,
      fadeFactor: state.fadeFactor,
      absActive: state.absActive,
      slipRatio: state.slipRatio
    };
  };

  BrakeSystem.prototype.deserializeBrake = function (vehicle, data) {
    const state = this.ensureBrake(vehicle);
    if (!state || !data) return;
    if (typeof data.brakeTemp === 'number') state.brakeTemp = data.brakeTemp;
    if (typeof data.brakeForce === 'number') state.brakeForce = data.brakeForce;
    if (typeof data.fadeFactor === 'number') state.fadeFactor = data.fadeFactor;
    if (typeof data.absActive === 'boolean') state.absActive = data.absActive;
    if (typeof data.slipRatio === 'number') state.slipRatio = data.slipRatio;
  };

  BrakeSystem.prototype.serialize = function () {
    const data = {};
    for (const [id, state] of this._vehicles) {
      data[id] = {
        brakeTemp: state.brakeTemp,
        brakeForce: state.brakeForce,
        fadeFactor: state.fadeFactor,
        absActive: state.absActive,
        slipRatio: state.slipRatio
      };
    }
    return data;
  };

  BrakeSystem.prototype.deserialize = function (data) {
    if (!data || typeof data !== 'object') return;
    for (const [id, stateData] of Object.entries(data)) {
      let existing = this._vehicles.get(id);
      if (!existing) {
        existing = {
          __owner: this,
          mass: DEFAULT_BRAKE.mass,
          maxBrakeForce: DEFAULT_BRAKE.maxBrakeForce,
          frontBias: DEFAULT_BRAKE.frontBias,
          brakeTempMax: DEFAULT_BRAKE.brakeTempMax,
          brakeTemp: DEFAULT_BRAKE.brakeTempStart,
          brakeTempStart: DEFAULT_BRAKE.brakeTempStart,
          fadeStartTemp: DEFAULT_BRAKE.fadeStartTemp,
          fadeMaxTemp: DEFAULT_BRAKE.fadeMaxTemp,
          fadeMinFactor: DEFAULT_BRAKE.fadeMinFactor,
          coolingRate: DEFAULT_BRAKE.coolingRate,
          idleCoolingRate: DEFAULT_BRAKE.idleCoolingRate,
          absSlipThreshold: DEFAULT_BRAKE.absSlipThreshold,
          absRestoreRate: DEFAULT_BRAKE.absRestoreRate,
          absMaxCycles: DEFAULT_BRAKE.absMaxCycles,
          speed: 0,
          targetSpeed: 0,
          brakeInput: 0,
          handbrake: false,
          steering: 0,
          roadFriction: 1.0,
          frontLoad: 0,
          rearLoad: 0,
          brakeForce: 0,
          frontBrakeForce: 0,
          rearBrakeForce: 0,
          deceleration: 0,
          fadeFactor: 1.0,
          absActive: false,
          slipRatio: 0
        };
        this._vehicles.set(id, existing);
      }
      if (typeof stateData.brakeTemp === 'number') existing.brakeTemp = stateData.brakeTemp;
      if (typeof stateData.brakeForce === 'number') existing.brakeForce = stateData.brakeForce;
      if (typeof stateData.fadeFactor === 'number') existing.fadeFactor = stateData.fadeFactor;
      if (typeof stateData.absActive === 'boolean') existing.absActive = stateData.absActive;
      if (typeof stateData.slipRatio === 'number') existing.slipRatio = stateData.slipRatio;
    }
  };

  BrakeSystem.prototype.attachBrake = function (vehicle) {
    if (!vehicle) return null;
    const state = this._vehicles.get(vehicle.id);
    if (state) {
      vehicle._brake = state;
      return state;
    }
    return this.ensureBrake(vehicle);
  };

  BrakeSystem.prototype.destroy = function () {
    this._vehicles.clear();
    this._active = false;
  };

  if (typeof window !== 'undefined') {
    window.BusSim = window.BusSim || {};
    window.BusSim.BrakeSystem = BrakeSystem;
  }
  if (typeof module !== 'undefined') {
    module.exports = BrakeSystem;
  }
})();
